#ifndef MIDIPREREQUISITES_H
#define MIDIPREREQUISITES_H

#define MIDI_UNUSED(x) {(void)x;}

namespace midi {

enum MidiResult {
    OK,

    MIDI_UNIMPLEMENTED,

    MIDI_INPUT_DISABLED,
    MIDI_OUTPUT_DISABLED,

    MIDI_INPUT_NO_DEVICES,
    MIDI_OUTPUT_NO_DEVICES,

    MIDI_INPUT_DEVICE_ID_NOT_FOUND,
    MIDI_OUTPUT_DEVICE_ID_NOT_FOUND,
    MIDI_DEVICE_ID_NOT_FOUND,

    MIDI_INPUT_OUTPUT_DEVICE_MISMATCH,

    BACKEND_CREATION_ERROR,
    UNKNOWN_API,
    BACKEND_ERROR,
};

enum MidiType {
    INPUT,
    OUTPUT,
};

}

#endif // MIDIPREREQUISITES_H
