#!/bin/bash
# requrires to install xdotool
#
echo "running doxygen and opening firefox browser"
doxygen Doxyfile > doxy.log
SERVICE='firefox'
if ps ax | grep -v grep | grep $SERVICE > /dev/null
then
	# refresh open windows
    xdotool windowactivate `xdotool search --name "Mozilla Firefox" | head -1`
    xdotool key F5
else
	# open window
	firefox html/index.html 
fi
