#!/bin/bash
# requrires to install xdotools
#
echo "running doxygen and opening firefox browser"
mkdir doxy
doxygen Doxyfile
SERVICE='firefox'
if ps ax | grep -v grep | grep $SERVICE > /dev/null
then
	# refresh open windows
    xdotool windowactivate `xdotool search --name "Mozilla Firefox" | head -1`
    xdotool key F5
else
	# open window
	firefox doxy/html/index.html 
fi